### ISSUE TITLE
Crash when Ore Entities are Killed by Non-players

### ISSUE THREAD

**Issue by frodare** [elias54/Fake-Ores-2#5]
This was brought to my attention by: https://github.com/ToroCraft/ToroQuest/issues/167
It looks like an `instanceof` check is needed here: https://github.com/elias54/Fake-Ores-2/blob/master/src/main/java/fr/elias/common/EntityOres.java#L16

Crash Report: https://gist.github.com/NoplixDE/a5a2e3e2e1064d901bae6a339959c7a3

Cheers

**Comment by eliferd** [comment]
Fixed. Sorry for a late reply https://github.com/elias54/Fake-Ores-2/commit/f124102242f309ccd73a627a313ffb0fe0083bf2
